### ISSUE TITLE
Pls update

### ISSUE THREAD

**Issue by ajaxxxxxxx** [atthematyo/hoi4_flag_maker#1]
I BEG to have this updated. I have broken my desk trying to install all these damn dependencies just to change the 10 in the outputted small flags to an 11. Pls update.

**Comment by atthematyo** [comment]
Hi @ajaxxxxxxx 

I updated the GUI so you can enter your own custom sizes. Hope this helps!

https://github.com/atthematyo/hoi4_flag_maker/releases/tag/1.1.0

![GUI](https://github.com/atthematyo/hoi4_flag_maker/assets/29811542/d124dde6-d504-4353-a9a1-1e1bddb0a748)
